# Generated by Django 3.1.2 on 2020-12-03 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kikify', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(max_length=255, upload_to='kikify/media/songs/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='picture',
            field=models.ImageField(upload_to='kikify/media/profile_pictures/'),
        ),
    ]
