# Generated by Django 3.1.2 on 2020-11-03 01:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('kikify', '0002_auto_20201030_0301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='bytes',
        ),
        migrations.AddField(
            model_name='file',
            name='1604366326632',
            field=models.FileField(default=django.utils.timezone.now, upload_to='uploads/%Y/%m/%d/'),
            preserve_default=False,
        ),
    ]
