# Generated by Django 3.1.2 on 2020-11-03 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kikify', '0003_auto_20201103_0219'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='1604366326632',
            new_name='file',
        ),
    ]
