# Generated by Django 3.1.2 on 2020-11-03 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kikify', '0004_auto_20201103_0224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to='media/songs/%Y/%m/%d/'),
        ),
    ]
