# Generated by Django 3.1.5 on 2021-02-25 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kikify', '0005_auto_20201203_1406'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kikify.userprofileinfo')),
            ],
        ),
        migrations.AddField(
            model_name='album',
            name='record_label',
            field=models.ManyToManyField(to='kikify.RecordLabel'),
        ),
    ]
