# Generated by Django 3.1.2 on 2020-11-03 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kikify', '0005_auto_20201103_0237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(max_length=255, upload_to='media/songs/%Y/%m/%d/'),
        ),
    ]
