# Generated by Django 3.1.2 on 2020-11-03 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kikify', '0006_auto_20201103_0238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='picture',
        ),
    ]
