# Generated by Django 3.1.5 on 2021-02-28 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kikify', '0010_auto_20210228_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(max_length=255, upload_to='C:/media/songs/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='recordlabel',
            name='picture',
            field=models.ImageField(upload_to='C:\\Users\\stepa\\Desktop\\Desktop (HP)\\kikify_django\\media\\profile_pictures/'),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='picture',
            field=models.ImageField(upload_to='C:\\Users\\stepa\\Desktop\\Desktop (HP)\\kikify_django\\media\\profile_pictures/'),
        ),
    ]
