# Generated by Django 3.1.5 on 2021-03-12 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kikify', '0014_auto_20210312_0257'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='artists',
            new_name='artist',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='albums',
        ),
    ]
